// Code generated by protoc-gen-go. DO NOT EDIT.
// source: catalog-movies-api.proto

package proto_management

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae7609195a8d74be, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type Movie struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Genre                string   `protobuf:"bytes,3,opt,name=genre,proto3" json:"genre,omitempty"`
	Director             string   `protobuf:"bytes,4,opt,name=director,proto3" json:"director,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Movie) Reset()         { *m = Movie{} }
func (m *Movie) String() string { return proto.CompactTextString(m) }
func (*Movie) ProtoMessage()    {}
func (*Movie) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae7609195a8d74be, []int{1}
}

func (m *Movie) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Movie.Unmarshal(m, b)
}
func (m *Movie) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Movie.Marshal(b, m, deterministic)
}
func (m *Movie) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Movie.Merge(m, src)
}
func (m *Movie) XXX_Size() int {
	return xxx_messageInfo_Movie.Size(m)
}
func (m *Movie) XXX_DiscardUnknown() {
	xxx_messageInfo_Movie.DiscardUnknown(m)
}

var xxx_messageInfo_Movie proto.InternalMessageInfo

func (m *Movie) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Movie) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Movie) GetGenre() string {
	if m != nil {
		return m.Genre
	}
	return ""
}

func (m *Movie) GetDirector() string {
	if m != nil {
		return m.Director
	}
	return ""
}

type Id struct {
	Value                int32    `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Id) Reset()         { *m = Id{} }
func (m *Id) String() string { return proto.CompactTextString(m) }
func (*Id) ProtoMessage()    {}
func (*Id) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae7609195a8d74be, []int{2}
}

func (m *Id) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Id.Unmarshal(m, b)
}
func (m *Id) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Id.Marshal(b, m, deterministic)
}
func (m *Id) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Id.Merge(m, src)
}
func (m *Id) XXX_Size() int {
	return xxx_messageInfo_Id.Size(m)
}
func (m *Id) XXX_DiscardUnknown() {
	xxx_messageInfo_Id.DiscardUnknown(m)
}

var xxx_messageInfo_Id proto.InternalMessageInfo

func (m *Id) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type MoviesListResponse struct {
	MoviesList           []*Movie `protobuf:"bytes,1,rep,name=moviesList,proto3" json:"moviesList,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MoviesListResponse) Reset()         { *m = MoviesListResponse{} }
func (m *MoviesListResponse) String() string { return proto.CompactTextString(m) }
func (*MoviesListResponse) ProtoMessage()    {}
func (*MoviesListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae7609195a8d74be, []int{3}
}

func (m *MoviesListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MoviesListResponse.Unmarshal(m, b)
}
func (m *MoviesListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MoviesListResponse.Marshal(b, m, deterministic)
}
func (m *MoviesListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MoviesListResponse.Merge(m, src)
}
func (m *MoviesListResponse) XXX_Size() int {
	return xxx_messageInfo_MoviesListResponse.Size(m)
}
func (m *MoviesListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MoviesListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MoviesListResponse proto.InternalMessageInfo

func (m *MoviesListResponse) GetMoviesList() []*Movie {
	if m != nil {
		return m.MoviesList
	}
	return nil
}

type MovieResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Movie                *Movie   `protobuf:"bytes,2,opt,name=movie,proto3" json:"movie,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MovieResponse) Reset()         { *m = MovieResponse{} }
func (m *MovieResponse) String() string { return proto.CompactTextString(m) }
func (*MovieResponse) ProtoMessage()    {}
func (*MovieResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae7609195a8d74be, []int{4}
}

func (m *MovieResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MovieResponse.Unmarshal(m, b)
}
func (m *MovieResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MovieResponse.Marshal(b, m, deterministic)
}
func (m *MovieResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MovieResponse.Merge(m, src)
}
func (m *MovieResponse) XXX_Size() int {
	return xxx_messageInfo_MovieResponse.Size(m)
}
func (m *MovieResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MovieResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MovieResponse proto.InternalMessageInfo

func (m *MovieResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *MovieResponse) GetMovie() *Movie {
	if m != nil {
		return m.Movie
	}
	return nil
}

func init() {
	proto.RegisterType((*Empty)(nil), "proto_management.Empty")
	proto.RegisterType((*Movie)(nil), "proto_management.Movie")
	proto.RegisterType((*Id)(nil), "proto_management.Id")
	proto.RegisterType((*MoviesListResponse)(nil), "proto_management.MoviesListResponse")
	proto.RegisterType((*MovieResponse)(nil), "proto_management.MovieResponse")
}

func init() { proto.RegisterFile("catalog-movies-api.proto", fileDescriptor_ae7609195a8d74be) }

var fileDescriptor_ae7609195a8d74be = []byte{
	// 346 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x51, 0xcf, 0x6b, 0xf2, 0x40,
	0x10, 0x25, 0xf1, 0x8b, 0x5f, 0x1d, 0xb5, 0x94, 0xc5, 0xb6, 0x21, 0x97, 0x4a, 0xe8, 0x21, 0x17,
	0x43, 0xb1, 0x87, 0x1e, 0x0a, 0x3d, 0x88, 0x52, 0x04, 0xbd, 0x44, 0xe8, 0xa1, 0x17, 0xd9, 0x26,
	0x43, 0xba, 0x90, 0x5f, 0x64, 0x47, 0xc1, 0x7f, 0xbe, 0x14, 0x77, 0x8d, 0x54, 0x6b, 0x5a, 0xe8,
	0x29, 0xbc, 0x97, 0x79, 0x6f, 0xde, 0x9b, 0x05, 0x3b, 0xe4, 0xc4, 0x93, 0x3c, 0x1e, 0xa4, 0xf9,
	0x5a, 0xa0, 0x1c, 0xf0, 0x42, 0xf8, 0x45, 0x99, 0x53, 0xce, 0x2e, 0xd4, 0x67, 0x99, 0xf2, 0x8c,
	0xc7, 0x98, 0x62, 0x46, 0xee, 0x7f, 0xb0, 0x26, 0x69, 0x41, 0x1b, 0x77, 0x09, 0xd6, 0x7c, 0x3b,
	0xce, 0xce, 0xc1, 0x14, 0x91, 0x6d, 0xf4, 0x0d, 0xcf, 0x0a, 0x4c, 0x11, 0xb1, 0x1e, 0x58, 0x24,
	0x28, 0x41, 0xdb, 0xec, 0x1b, 0x5e, 0x2b, 0xd0, 0x60, 0xcb, 0xc6, 0x98, 0x95, 0x68, 0x37, 0x34,
	0xab, 0x00, 0x73, 0xe0, 0x2c, 0x12, 0x25, 0x86, 0x94, 0x97, 0xf6, 0x3f, 0xf5, 0x63, 0x8f, 0x5d,
	0x07, 0xcc, 0xa9, 0x72, 0x5b, 0xf3, 0x64, 0x85, 0xbb, 0x05, 0x1a, 0xb8, 0x73, 0x60, 0x6a, 0xb9,
	0x9c, 0x09, 0x49, 0x01, 0xca, 0x22, 0xcf, 0x24, 0xb2, 0x07, 0x80, 0x74, 0xcf, 0xda, 0x46, 0xbf,
	0xe1, 0xb5, 0x87, 0xd7, 0xfe, 0x71, 0x05, 0x5f, 0x29, 0x83, 0x2f, 0xa3, 0xee, 0x0b, 0x74, 0x35,
	0x59, 0x39, 0x5d, 0x41, 0x53, 0x12, 0xa7, 0x95, 0x54, 0x6b, 0x5b, 0xc1, 0x0e, 0xb1, 0x01, 0x58,
	0x4a, 0xa6, 0xba, 0xfd, 0x60, 0xae, 0xa7, 0x86, 0x1f, 0x26, 0x74, 0x14, 0xb1, 0xc0, 0x72, 0x2d,
	0x42, 0x64, 0x33, 0x68, 0x3d, 0x23, 0xe9, 0xe8, 0xec, 0x84, 0x5a, 0x9d, 0xd6, 0xb9, 0xad, 0xb1,
	0x3d, 0x68, 0x7b, 0x67, 0xb0, 0x09, 0x74, 0x2a, 0xb7, 0xd1, 0x66, 0x7b, 0xab, 0xef, 0xba, 0x69,
	0xe4, 0xdc, 0xd4, 0x85, 0xac, 0xca, 0x3e, 0x41, 0x37, 0xc0, 0x58, 0x48, 0xc2, 0x52, 0xbf, 0x68,
	0x5d, 0x2d, 0xe7, 0xe4, 0x02, 0xb6, 0x80, 0xcb, 0x03, 0xbd, 0x9c, 0x66, 0x23, 0x4e, 0xe1, 0x7b,
	0xbd, 0xcf, 0x6f, 0x91, 0x3c, 0x83, 0x8d, 0xa1, 0x3d, 0xc6, 0x04, 0x09, 0x75, 0xa4, 0xbf, 0x55,
	0x1b, 0xf5, 0x5e, 0x99, 0xff, 0x78, 0x3c, 0xf3, 0xd6, 0x54, 0xcc, 0xfd, 0x67, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xb3, 0x5b, 0x80, 0x05, 0xf8, 0x02, 0x00, 0x00,
}
